"""add senha to users

Revision ID: 1660c3d68cea
Revises: 5c7c11b31a18
Create Date: 2026-06-15 00:39:29.461644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1660c3d68cea'
down_revision: Union[str, Sequence[str], None] = '5c7c11b31a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('senha', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'senha')
    # ### end Alembic commands ###
