"""create emprestimos table

Revision ID: c2338a5057d6
Revises: 877d76332dab
Create Date: 2026-06-17 02:41:50.902747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2338a5057d6'
down_revision: Union[str, Sequence[str], None] = '877d76332dab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emprestimos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('jogo_id', sa.Integer(), nullable=False),
    sa.Column('data_emprestimo', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_devolucao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('devolvido', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['jogo_id'], ['jogos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emprestimos_id'), 'emprestimos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emprestimos_id'), table_name='emprestimos')
    op.drop_table('emprestimos')
    # ### end Alembic commands ###
